---
title: "Djamaldbz - Classification binaire en utilisant la SVM !!!"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE)
library(reticulate)
use_python("C:/Users/Djamal TOE/AppData/Local/Programs/Python/Python311")
```


::: {#wolframalfa .callout-important} 
# Comment cela fonctionne

Je tiens tout d'abord à rapperler que je n'utilise pas de modèle **NLP** pour créer ce petit assistant virtuel. J'avais écris ce progamme en 2021, donc bien evidemment les outils utilisés ont évolué et donc vous pourrez l'ajuster à votre guise. Le code source sera téléchargeable à la fin de la page.
:::

# Introduction

|       Après mon cours d'**optimisation et méthode numérique** à l'ENSAI, je me suis proposé d'écrire un modèle de classification binaire. En particulier j'ai souhaité classifier des clients .... en utilisant les ***Séparateurs à Vastes Marges***. J'ai dévéloppé une interface desktop avec le package `costumtkinter` et une application web shiny hébergée sur mon server. Voici le lien : 


## LA SVM : C'est quoi et à quoi ça sert ?



### Utilité :



### Principe de la SVM pour la classification binaire



## Test du code

{{< video https://djamal2905.github.io/djamal_website/INFO_MINI_PROJETS/assistant.mp4 >}}

## Conclusion

Ce code met en place un assistant vocal capable de reconnaître et d'exécuter des commandes vocales en français, d'effectuer des recherches sur le web, et de répondre aux questions grâce à Wolfram Alpha et Wikipédia. Il constitue une base quelque peu solide pour un assistant personnel plus ou moins intelligent.


[**Télécharger le fichier .python**](https://djamal2905.github.io/djamal_website/INFO_MINI_PROJETS/chat.py)

[**Télécharger la vidéo**](https://djamal2905.github.io/djamal_website/INFO_MINI_PROJETS/assistant.mp4)

Si vous avez des questions, vous pouvez me contacter !!!

[Retour à la page d'accueuil](https://djamal2905.github.io/djamal_website)