project:
  type: website
  output-dir: docs
  resources:
    - images


website:
  title: "DJAMAL SITE"
  navbar:
    logo: images/logo.png
    logo-href: index.qmd
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Statistic
        menu: 
          - href: ANALYSES_FACTORIELLES/TP03.qmd
            text: Analyse en Composantes Principales et Analyse Factorielle Multiple
      - text: Programming
        menu: 
          - href: INFO_MINI_PROJETS/assistant_virtuel.qmd
            text: Crée ton assistant virtuel avec pyhton
      - text: About me
        href: about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true



