project:
  type: website
  output-dir: docs
  resources:
    - images
    - INFO_MINI_PROJETS/assistant.mp4


website:
  title: "DJAMAL SITE"
  navbar:
    logo: images/logo.png
    logo-href: index.qmd
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Statistics
        menu: 
          - href: ANALYSES_FACTORIELLES/TP03.qmd
            text: Analyse en Composantes Principales et Analyse Factorielle Multiple
          - href: FORMATIONS/poisson_paludisme.qmd
            text: Modélisation des données de comptage
          - href: FORMATIONS/logistic_regression_diabetes.qmd
            text: Modélisation des données à variables dépendantes binaires
      - text: Programming
        menu: 
          - href: INFO_MINI_PROJETS/assistant_virtuel.qmd
            text: Crée ton assistant virtuel avec pyhton
      - text: About me
        href: about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true



