project:
  type: website
  output-dir: docs
  resources:
    - images
    - INFO_MINI_PROJETS/
    - projet-traitement-donnees
    - FORMATIONS


website:
  title: "DJAMAL SITE"
  navbar:
    logo: images/logo.png
    logo-href: index.qmd
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: Statistics & Machine Learning
        menu: 
          - href: projet-traitement-donnees/report_writing/synthese-des-travaux.qmd
            text: Prédire la durée de carrière des joueurs NBA
          - href: FORMATIONS/poisson_paludisme.qmd
            text: Modélisation des données de comptage
          - href: INFO_MINI_PROJETS/shifumi-cnn-yolov8.qmd
            text: Classification des gestes de la main avec Yolo et CNN
          - href: FORMATIONS/logistic_regression_diabetes.qmd
            text: Modélisation des données à variables dépendantes binaires
      - text: Programming
        menu: 
          - href: INFO_MINI_PROJETS/assistant_virtuel.qmd
            text: Crée ton assistant virtuel avec pyhton
      - text: About me
        href: about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true



