project:
  type: website
  output-dir: docs
  resources:
    - "images"
    - "ANALYSES_FACTORIELLES"
    - "FORMATIONS"
    - "INFO_MINI_PROJETS"


website:
  title: "DJAMAL SITE"
  navbar:
    logo: images/logo.png
    logo-href: index.qmd
    left:
      - href: index.qmd
        text: Home
  
      - text: A propos de moi
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



